# Generated by Django 4.0.3 on 2022-03-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySQLRestApp', '0002_customer_city_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=200),
        ),
    ]
